[package]
name = "radb"
description = "A distributed SQL Database"
version = "0.1.0"
authors = ["Radhesh Goel <Radhesh036916@gmail.com>"]
edition = "2021"
default-run = "radb"

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bincode = "~1.3.3"
clap = { version = "~4.5.4", features = ["cargo", "derive"] }
config = "~0.14.0"
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
derivative = "~2.2.0"
fs4 = "~0.8.1"
hdrhistogram = "~7.5.4"
hex = "~0.4.3"
itertools = "0.12.1"
log = "~0.4.14"
petname = "1.1.3"
rand = "~0.8.3"
regex = "1.5.4"
rustyline = "~14.0.0"
rustyline-derive = "~0.10.0"
serde = "~1.0.126"
serde_bytes = "~0.11.12"
serde_derive = "~1.0.126"
simplelog = "~0.12.1"
uuid = { version = "~1.8.0", features = ["v4"] }

[dev-dependencies]
escargot = "0.5.10"
goldenfile = "~1.6.0"
paste = "~1.0.14"
pretty_assertions = "~1.4.0"
serial_test = "~3.0.0"
tempdir = "~0.3.7"
tempfile = "~3.10.1"